### ISSUE TITLE
First vizualization window fails to initiate

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/Seg3D#180]
The first visualization window fails to intiate upon loading a new/previous project or changing the view settings. I have tested the visualization with both QT 5.5.1 and QT 5.7.0 and it was the same issue.  

![seg3d_viewer_init](https://cloud.githubusercontent.com/assets/12956701/21885006/1859f1c0-d8b6-11e6-8b49-cf17fb8d6a0d.png)

**Comment by kgillette** [comment]
My OS is CentOs Linux 7. Both version of qt5 were compiled from source code, however the 5.5 version was compiled using the 5.5 branch from the git repo https://github.com/qt/qt5.

**Comment by aylakhan** [comment]
Doesn't appear to be a problem on Windows, but this will need more testing...

**Comment by kgillette** [comment]
I will see if anyone else here in the lab has compiled it and is running a different Linux OS than me. I'll also try it on my MacBook.

**Comment by kasia21** [comment]
I am experiencing the same issue using RHEL 7 and Qt 5.8.1. I built the latest Seg3D v2.4.0 RC4. I compiled Qt5 from the git repo. Please let me know if you need further information to help with diagnosing.

**Comment by aylakhan** [comment]
Can you test this with a build that uses Qt 5.9?

**Comment by kgillette** [comment]
I just tested it with Qt 5.9, but got the same initialization error. The only way that I can get around it is to add an additional viewing window and then minimize it. Another member in my lab that built with Qt 5.8 and has Ubuntu got the same initialization problem.

**Comment by aylakhan** [comment]
Thank you for testing that. That probably narrows the bug down to OpenGL or the Renderer initialization code in general.

**Comment by jessdtate** [comment]
I see this in the latest master builds now in os x 10.12 and 10.10

**Comment by jessdtate** [comment]
this should be fixed in master now.  Please test.  @kgillette

**Comment by markusfoote** [comment]
I'm still seeing this issue on 2.4.2 and master(0947cb5), both with Qt 5.9.3 (prebuilt from Qt) on openSuse 42.3. Are there any useful logs/info I can provide?

**Comment by kgillette** [comment]
I just tested this on my system again and I am also getting the same issue on the master branch. I am working with qt 5.9 from source on Cent OS 7 on master branch 0947cb5.

**Comment by mildewey** [comment]
I'm not able to reproduce this on Ubuntu 18.04 and the latest build, 2.4.2. Are any of the original reporters still able to reproduce this? Is the issue sporadic? or consistent?

My attempt to reproduce included loading a simple project in various ways and changing the view settings around in various ways, eg going to full screen or changing the set of displays.

**Comment by kgillette** [comment]
I am still consistently having this issue even though I just updated to the latest build. All I have to do is open a new project and load a file. The first window always fails to initiate so I must change the views to two and three and then delete the first window. 

I am running on Cent OS 7, but was planning to switch to Ubunut 18.04.

**Comment by kasia21** [comment]
Hi everyone,

I just built Seg3D 2.4.2 from source on 64-bit RHEL 7.5 and all of the
windows were able to initialize for me, which was not the case with Seg 3D
2.4. For the build, my C compiler is GNU 4.8.5 and Qt version 5.9.3.

Thanks very much and please let me know if I can provide further
information to help.

-Katie

**Comment by mildewey** [comment]
I am struggling to build Seg3D at all on Centos 7 so I can more thoroughly diagnose this issue. Those of you who succeeded, do you have notes on what you had to install to get everything working? Specifically I'm stuck on building GLEW as it doesn't seem to find the OpenGL libraries (despite having the mesa libraries installed).

**Comment by allywarner** [comment]
This was seen at iBBM on OS X 10.13.

**Comment by allywarner** [comment]
This should be fixed with pull request #305.
